name: AxiomVault
options:
  bundleIdPrefix: com.axiomvault
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: bottom
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: NO
    DEAD_CODE_STRIPPING: YES

targets:
  AxiomVault:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: AxiomVault/Sources
        type: group
        excludes:
          - "**/.DS_Store"

    resources:
      - path: AxiomVault/Resources/Assets.xcassets
      - path: AxiomVault/Resources/Info.plist
        buildPhase: none

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.axiomvault.ios
        INFOPLIST_FILE: AxiomVault/Resources/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: AxiomVault/Sources/Core/AxiomVault-Bridging-Header.h
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-lresolv"
          - "-lSystem"
          - "-lc++"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/Frameworks"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/Frameworks"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

    dependencies:
      - framework: Frameworks/AxiomVaultCore.xcframework
        embed: false

    entitlements:
      path: AxiomVault/Resources/AxiomVault.entitlements
      properties:
        com.apple.security.application-groups:
          - "group.com.axiomvault.ios"
        keychain-access-groups:
          - "$(AppIdentifierPrefix)com.axiomvault.ios"

    preBuildScripts:
      - name: "Check Rust Framework"
        script: |
          if [ ! -d "${PROJECT_DIR}/Frameworks/AxiomVaultCore.xcframework" ]; then
            echo "error: AxiomVaultCore.xcframework not found. Run 'Scripts/build-ios.sh' first."
            exit 1
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false

schemes:
  AxiomVault:
    build:
      targets:
        AxiomVault: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
