//
//  AxiomVault-Bridging-Header.h
//  AxiomVault
//
//  Bridging header for AxiomVault iOS client.
//  This imports the C FFI header generated by cbindgen.
//

#ifndef AxiomVault_Bridging_Header_h
#define AxiomVault_Bridging_Header_h

#import <Foundation/Foundation.h>

// Forward declaration for opaque handle type
typedef struct VaultHandleData VaultHandleData;

// Type alias for opaque vault handle
typedef VaultHandleData FFIVaultHandle;

// Vault information structure
typedef struct {
    const char *vault_id;
    const char *root_path;
    int file_count;
    long long total_size;
    int version;
} FFIVaultInfo;

// FFI function declarations
int axiom_init(void);
const char *axiom_version(void);

FFIVaultHandle *axiom_vault_create(const char *path, const char *password);
FFIVaultHandle *axiom_vault_open(const char *path, const char *password);
int axiom_vault_close(FFIVaultHandle *handle);

FFIVaultInfo *axiom_vault_info(const FFIVaultHandle *handle);
void axiom_vault_info_free(FFIVaultInfo *info);

char *axiom_vault_list(const FFIVaultHandle *handle, const char *path);

int axiom_vault_add_file(const FFIVaultHandle *handle,
                          const char *local_path,
                          const char *vault_path);

int axiom_vault_extract_file(const FFIVaultHandle *handle,
                              const char *vault_path,
                              const char *local_path);

int axiom_vault_mkdir(const FFIVaultHandle *handle, const char *vault_path);

int axiom_vault_remove(const FFIVaultHandle *handle, const char *vault_path);

int axiom_vault_change_password(const FFIVaultHandle *handle,
                                 const char *old_password,
                                 const char *new_password);

char *axiom_last_error(void);
void axiom_string_free(char *s);

#endif /* AxiomVault_Bridging_Header_h */
